testcase office_ria_animation:
    pause until screen "main_menu"
    $ _ria_old_cps = preferences.text_cps
    run Preference("text speed",0)
    click "첫날 시작"
    $ _ria_old_motion = persistent.reduce_motion
    $ _ria_old_animation = persistent.ria_animation
    run SetField(persistent,"reduce_motion",False)
    run SetField(persistent,"ria_animation",True)
    advance until screen "choice"
    run Function(ui_pose_set,"ria","casual")
    run Function(ui_expression_set,"ria","smile")
    run Function(ui_camera_set,"C")
    run SetVariable("ui_ria_preview_time",0.0)
    pause 0.6
    move pos (20,20)
    assert eval ui_ria_animation_active()
    run SetVariable("ui_ria_eye_override","open")
    pause 0.08
    assert eval ui_ria_eye_state() == "open"
    screenshot "ria_animation_open_v1"
    run SetVariable("ui_ria_eye_override","half")
    pause 0.08
    assert eval ui_ria_eye_state() == "half"
    screenshot "ria_animation_half_v1"
    run SetVariable("ui_ria_eye_override","closed")
    pause 0.08
    assert eval ui_ria_eye_state() == "closed"
    screenshot "ria_animation_closed_v1"
    run SetVariable("ui_ria_eye_override",None)
    run SetVariable("ui_ria_preview_time",2.41)
    pause 0.08
    assert eval ui_ria_eye_state() == "closed"
    screenshot "ria_animation_auto_head_v1"
    run SetField(persistent,"reduce_motion",True)
    pause 0.1
    assert eval not ui_ria_animation_active()
    screenshot "ria_animation_reduced_motion_v1"
    run SetField(persistent,"reduce_motion",False)
    run SetField(persistent,"ria_animation",False)
    assert eval not ui_ria_animation_active()
    run SetField(persistent,"ria_animation",True)
    run SetVariable("ui_ria_preview_time",0.0)
    run FilePage("ria-motion-qa")
    run Function(renpy.retain_after_load)
    run FileSave(1,confirm=False)
    run OfficeFileLoad(1,confirm=False)
    assert eval ui_pose_current("ria") == "casual" and ui_ria_animation_active()
    run FileDelete(1,confirm=False)
    run FilePage(1)
    run SetVariable("ui_ria_preview_time",0.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_000.png")
    run SetVariable("ui_ria_preview_time",0.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_001.png")
    run SetVariable("ui_ria_preview_time",0.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_002.png")
    run SetVariable("ui_ria_preview_time",0.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_003.png")
    run SetVariable("ui_ria_preview_time",0.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_004.png")
    run SetVariable("ui_ria_preview_time",0.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_005.png")
    run SetVariable("ui_ria_preview_time",0.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_006.png")
    run SetVariable("ui_ria_preview_time",0.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_007.png")
    run SetVariable("ui_ria_preview_time",0.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_008.png")
    run SetVariable("ui_ria_preview_time",0.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_009.png")
    run SetVariable("ui_ria_preview_time",0.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_010.png")
    run SetVariable("ui_ria_preview_time",0.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_011.png")
    run SetVariable("ui_ria_preview_time",0.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_012.png")
    run SetVariable("ui_ria_preview_time",0.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_013.png")
    run SetVariable("ui_ria_preview_time",0.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_014.png")
    run SetVariable("ui_ria_preview_time",0.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_015.png")
    run SetVariable("ui_ria_preview_time",1.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_016.png")
    run SetVariable("ui_ria_preview_time",1.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_017.png")
    run SetVariable("ui_ria_preview_time",1.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_018.png")
    run SetVariable("ui_ria_preview_time",1.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_019.png")
    run SetVariable("ui_ria_preview_time",1.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_020.png")
    run SetVariable("ui_ria_preview_time",1.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_021.png")
    run SetVariable("ui_ria_preview_time",1.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_022.png")
    run SetVariable("ui_ria_preview_time",1.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_023.png")
    run SetVariable("ui_ria_preview_time",1.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_024.png")
    run SetVariable("ui_ria_preview_time",1.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_025.png")
    run SetVariable("ui_ria_preview_time",1.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_026.png")
    run SetVariable("ui_ria_preview_time",1.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_027.png")
    run SetVariable("ui_ria_preview_time",1.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_028.png")
    run SetVariable("ui_ria_preview_time",1.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_029.png")
    run SetVariable("ui_ria_preview_time",1.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_030.png")
    run SetVariable("ui_ria_preview_time",1.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_031.png")
    run SetVariable("ui_ria_preview_time",2.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_032.png")
    run SetVariable("ui_ria_preview_time",2.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_033.png")
    run SetVariable("ui_ria_preview_time",2.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_034.png")
    run SetVariable("ui_ria_preview_time",2.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_035.png")
    run SetVariable("ui_ria_preview_time",2.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_036.png")
    run SetVariable("ui_ria_preview_time",2.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_037.png")
    run SetVariable("ui_ria_preview_time",2.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_038.png")
    run SetVariable("ui_ria_preview_time",2.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_039.png")
    run SetVariable("ui_ria_preview_time",2.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_040.png")
    run SetVariable("ui_ria_preview_time",2.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_041.png")
    run SetVariable("ui_ria_preview_time",2.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_042.png")
    run SetVariable("ui_ria_preview_time",2.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_043.png")
    run SetVariable("ui_ria_preview_time",2.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_044.png")
    run SetVariable("ui_ria_preview_time",2.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_045.png")
    run SetVariable("ui_ria_preview_time",2.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_046.png")
    run SetVariable("ui_ria_preview_time",2.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_047.png")
    run SetVariable("ui_ria_preview_time",3.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_048.png")
    run SetVariable("ui_ria_preview_time",3.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_049.png")
    run SetVariable("ui_ria_preview_time",3.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_050.png")
    run SetVariable("ui_ria_preview_time",3.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_051.png")
    run SetVariable("ui_ria_preview_time",3.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_052.png")
    run SetVariable("ui_ria_preview_time",3.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_053.png")
    run SetVariable("ui_ria_preview_time",3.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_054.png")
    run SetVariable("ui_ria_preview_time",3.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_055.png")
    run SetVariable("ui_ria_preview_time",3.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_056.png")
    run SetVariable("ui_ria_preview_time",3.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_057.png")
    run SetVariable("ui_ria_preview_time",3.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_058.png")
    run SetVariable("ui_ria_preview_time",3.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_059.png")
    run SetVariable("ui_ria_preview_time",3.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_060.png")
    run SetVariable("ui_ria_preview_time",3.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_061.png")
    run SetVariable("ui_ria_preview_time",3.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_062.png")
    run SetVariable("ui_ria_preview_time",3.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_063.png")
    run SetVariable("ui_ria_preview_time",4.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_064.png")
    run SetVariable("ui_ria_preview_time",4.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_065.png")
    run SetVariable("ui_ria_preview_time",4.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_066.png")
    run SetVariable("ui_ria_preview_time",4.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_067.png")
    run SetVariable("ui_ria_preview_time",4.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_068.png")
    run SetVariable("ui_ria_preview_time",4.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_069.png")
    run SetVariable("ui_ria_preview_time",4.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_070.png")
    run SetVariable("ui_ria_preview_time",4.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_071.png")
    run SetVariable("ui_ria_preview_time",4.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_072.png")
    run SetVariable("ui_ria_preview_time",4.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_073.png")
    run SetVariable("ui_ria_preview_time",4.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_074.png")
    run SetVariable("ui_ria_preview_time",4.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_075.png")
    run SetVariable("ui_ria_preview_time",4.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_076.png")
    run SetVariable("ui_ria_preview_time",4.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_077.png")
    run SetVariable("ui_ria_preview_time",4.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_078.png")
    run SetVariable("ui_ria_preview_time",4.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_079.png")
    run SetVariable("ui_ria_preview_time",5.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_080.png")
    run SetVariable("ui_ria_preview_time",5.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_081.png")
    run SetVariable("ui_ria_preview_time",5.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_082.png")
    run SetVariable("ui_ria_preview_time",5.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_083.png")
    run SetVariable("ui_ria_preview_time",5.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_084.png")
    run SetVariable("ui_ria_preview_time",5.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_085.png")
    run SetVariable("ui_ria_preview_time",5.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_086.png")
    run SetVariable("ui_ria_preview_time",5.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_087.png")
    run SetVariable("ui_ria_preview_time",5.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_088.png")
    run SetVariable("ui_ria_preview_time",5.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_089.png")
    run SetVariable("ui_ria_preview_time",5.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_090.png")
    run SetVariable("ui_ria_preview_time",5.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_091.png")
    run SetVariable("ui_ria_preview_time",5.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_092.png")
    run SetVariable("ui_ria_preview_time",5.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_093.png")
    run SetVariable("ui_ria_preview_time",5.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_094.png")
    run SetVariable("ui_ria_preview_time",5.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_095.png")
    run SetVariable("ui_ria_preview_time",6.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_096.png")
    run SetVariable("ui_ria_preview_time",6.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_097.png")
    run SetVariable("ui_ria_preview_time",6.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_098.png")
    run SetVariable("ui_ria_preview_time",6.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_099.png")
    run SetVariable("ui_ria_preview_time",6.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_100.png")
    run SetVariable("ui_ria_preview_time",6.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_101.png")
    run SetVariable("ui_ria_preview_time",6.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_102.png")
    run SetVariable("ui_ria_preview_time",6.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_103.png")
    run SetVariable("ui_ria_preview_time",6.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_104.png")
    run SetVariable("ui_ria_preview_time",6.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_105.png")
    run SetVariable("ui_ria_preview_time",6.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_106.png")
    run SetVariable("ui_ria_preview_time",6.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_107.png")
    run SetVariable("ui_ria_preview_time",6.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_108.png")
    run SetVariable("ui_ria_preview_time",6.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_109.png")
    run SetVariable("ui_ria_preview_time",6.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_110.png")
    run SetVariable("ui_ria_preview_time",6.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_111.png")
    run SetVariable("ui_ria_preview_time",7.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_112.png")
    run SetVariable("ui_ria_preview_time",7.0625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_113.png")
    run SetVariable("ui_ria_preview_time",7.1250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_114.png")
    run SetVariable("ui_ria_preview_time",7.1875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_115.png")
    run SetVariable("ui_ria_preview_time",7.2500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_116.png")
    run SetVariable("ui_ria_preview_time",7.3125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_117.png")
    run SetVariable("ui_ria_preview_time",7.3750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_118.png")
    run SetVariable("ui_ria_preview_time",7.4375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_119.png")
    run SetVariable("ui_ria_preview_time",7.5000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_120.png")
    run SetVariable("ui_ria_preview_time",7.5625)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_121.png")
    run SetVariable("ui_ria_preview_time",7.6250)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_122.png")
    run SetVariable("ui_ria_preview_time",7.6875)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_123.png")
    run SetVariable("ui_ria_preview_time",7.7500)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_124.png")
    run SetVariable("ui_ria_preview_time",7.8125)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_125.png")
    run SetVariable("ui_ria_preview_time",7.8750)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_126.png")
    run SetVariable("ui_ria_preview_time",7.9375)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_127.png")
    run SetVariable("ui_ria_preview_time",8.0000)
    pause 0.04
    $ renpy.screenshot(r"C:\Users\user\AppData\Local\Temp\office-ria-motion-frames/frame_128.png")
    run Function(ui_phone_call_begin,"ria","ui_d1_call_done")
    pause 0.1
    assert eval not ui_ria_animation_active()
    assert eval renpy.get_displayable("office_portrait","office_character") is None
    run Function(ui_phone_call_end)
    run SetField(persistent,"reduce_motion",_ria_old_motion)
    run SetField(persistent,"ria_animation",_ria_old_animation)
    run SetVariable("ui_ria_eye_override",None)
    run SetVariable("ui_ria_preview_time",None)
    run Preference("text speed",_ria_old_cps)
    exit
